# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.13

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/smarek/Documents/PROJEKTY/DMR/HyteraIPSC_IPMSC/GIT/TOOLS/linDmrMaster

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/smarek/Documents/PROJEKTY/DMR/HyteraIPSC_IPMSC/GIT/TOOLS/linDmrMaster

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/smarek/Documents/PROJEKTY/DMR/HyteraIPSC_IPMSC/GIT/TOOLS/linDmrMaster/CMakeFiles /home/smarek/Documents/PROJEKTY/DMR/HyteraIPSC_IPMSC/GIT/TOOLS/linDmrMaster/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/smarek/Documents/PROJEKTY/DMR/HyteraIPSC_IPMSC/GIT/TOOLS/linDmrMaster/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named linDMR

# Build rule for target.
linDMR: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 linDMR
.PHONY : linDMR

# fast build rule for target.
linDMR/fast:
	$(MAKE) -f CMakeFiles/linDMR.dir/build.make CMakeFiles/linDMR.dir/build
.PHONY : linDMR/fast

BPTC1969.o: BPTC1969.c.o

.PHONY : BPTC1969.o

# target to build an object file
BPTC1969.c.o:
	$(MAKE) -f CMakeFiles/linDMR.dir/build.make CMakeFiles/linDMR.dir/BPTC1969.c.o
.PHONY : BPTC1969.c.o

BPTC1969.i: BPTC1969.c.i

.PHONY : BPTC1969.i

# target to preprocess a source file
BPTC1969.c.i:
	$(MAKE) -f CMakeFiles/linDMR.dir/build.make CMakeFiles/linDMR.dir/BPTC1969.c.i
.PHONY : BPTC1969.c.i

BPTC1969.s: BPTC1969.c.s

.PHONY : BPTC1969.s

# target to generate assembly for a file
BPTC1969.c.s:
	$(MAKE) -f CMakeFiles/linDMR.dir/build.make CMakeFiles/linDMR.dir/BPTC1969.c.s
.PHONY : BPTC1969.c.s

aprs.o: aprs.c.o

.PHONY : aprs.o

# target to build an object file
aprs.c.o:
	$(MAKE) -f CMakeFiles/linDMR.dir/build.make CMakeFiles/linDMR.dir/aprs.c.o
.PHONY : aprs.c.o

aprs.i: aprs.c.i

.PHONY : aprs.i

# target to preprocess a source file
aprs.c.i:
	$(MAKE) -f CMakeFiles/linDMR.dir/build.make CMakeFiles/linDMR.dir/aprs.c.i
.PHONY : aprs.c.i

aprs.s: aprs.c.s

.PHONY : aprs.s

# target to generate assembly for a file
aprs.c.s:
	$(MAKE) -f CMakeFiles/linDMR.dir/build.make CMakeFiles/linDMR.dir/aprs.c.s
.PHONY : aprs.c.s

convbin.o: convbin.c.o

.PHONY : convbin.o

# target to build an object file
convbin.c.o:
	$(MAKE) -f CMakeFiles/linDMR.dir/build.make CMakeFiles/linDMR.dir/convbin.c.o
.PHONY : convbin.c.o

convbin.i: convbin.c.i

.PHONY : convbin.i

# target to preprocess a source file
convbin.c.i:
	$(MAKE) -f CMakeFiles/linDMR.dir/build.make CMakeFiles/linDMR.dir/convbin.c.i
.PHONY : convbin.c.i

convbin.s: convbin.c.s

.PHONY : convbin.s

# target to generate assembly for a file
convbin.c.s:
	$(MAKE) -f CMakeFiles/linDMR.dir/build.make CMakeFiles/linDMR.dir/convbin.c.s
.PHONY : convbin.c.s

decode34Rate.o: decode34Rate.c.o

.PHONY : decode34Rate.o

# target to build an object file
decode34Rate.c.o:
	$(MAKE) -f CMakeFiles/linDMR.dir/build.make CMakeFiles/linDMR.dir/decode34Rate.c.o
.PHONY : decode34Rate.c.o

decode34Rate.i: decode34Rate.c.i

.PHONY : decode34Rate.i

# target to preprocess a source file
decode34Rate.c.i:
	$(MAKE) -f CMakeFiles/linDMR.dir/build.make CMakeFiles/linDMR.dir/decode34Rate.c.i
.PHONY : decode34Rate.c.i

decode34Rate.s: decode34Rate.c.s

.PHONY : decode34Rate.s

# target to generate assembly for a file
decode34Rate.c.s:
	$(MAKE) -f CMakeFiles/linDMR.dir/build.make CMakeFiles/linDMR.dir/decode34Rate.c.s
.PHONY : decode34Rate.c.s

dmr.o: dmr.c.o

.PHONY : dmr.o

# target to build an object file
dmr.c.o:
	$(MAKE) -f CMakeFiles/linDMR.dir/build.make CMakeFiles/linDMR.dir/dmr.c.o
.PHONY : dmr.c.o

dmr.i: dmr.c.i

.PHONY : dmr.i

# target to preprocess a source file
dmr.c.i:
	$(MAKE) -f CMakeFiles/linDMR.dir/build.make CMakeFiles/linDMR.dir/dmr.c.i
.PHONY : dmr.c.i

dmr.s: dmr.c.s

.PHONY : dmr.s

# target to generate assembly for a file
dmr.c.s:
	$(MAKE) -f CMakeFiles/linDMR.dir/build.make CMakeFiles/linDMR.dir/dmr.c.s
.PHONY : dmr.c.s

hyteraDecode.o: hyteraDecode.c.o

.PHONY : hyteraDecode.o

# target to build an object file
hyteraDecode.c.o:
	$(MAKE) -f CMakeFiles/linDMR.dir/build.make CMakeFiles/linDMR.dir/hyteraDecode.c.o
.PHONY : hyteraDecode.c.o

hyteraDecode.i: hyteraDecode.c.i

.PHONY : hyteraDecode.i

# target to preprocess a source file
hyteraDecode.c.i:
	$(MAKE) -f CMakeFiles/linDMR.dir/build.make CMakeFiles/linDMR.dir/hyteraDecode.c.i
.PHONY : hyteraDecode.c.i

hyteraDecode.s: hyteraDecode.c.s

.PHONY : hyteraDecode.s

# target to generate assembly for a file
hyteraDecode.c.s:
	$(MAKE) -f CMakeFiles/linDMR.dir/build.make CMakeFiles/linDMR.dir/hyteraDecode.c.s
.PHONY : hyteraDecode.c.s

main.o: main.c.o

.PHONY : main.o

# target to build an object file
main.c.o:
	$(MAKE) -f CMakeFiles/linDMR.dir/build.make CMakeFiles/linDMR.dir/main.c.o
.PHONY : main.c.o

main.i: main.c.i

.PHONY : main.i

# target to preprocess a source file
main.c.i:
	$(MAKE) -f CMakeFiles/linDMR.dir/build.make CMakeFiles/linDMR.dir/main.c.i
.PHONY : main.c.i

main.s: main.c.s

.PHONY : main.s

# target to generate assembly for a file
main.c.s:
	$(MAKE) -f CMakeFiles/linDMR.dir/build.make CMakeFiles/linDMR.dir/main.c.s
.PHONY : main.c.s

rdac.o: rdac.c.o

.PHONY : rdac.o

# target to build an object file
rdac.c.o:
	$(MAKE) -f CMakeFiles/linDMR.dir/build.make CMakeFiles/linDMR.dir/rdac.c.o
.PHONY : rdac.c.o

rdac.i: rdac.c.i

.PHONY : rdac.i

# target to preprocess a source file
rdac.c.i:
	$(MAKE) -f CMakeFiles/linDMR.dir/build.make CMakeFiles/linDMR.dir/rdac.c.i
.PHONY : rdac.c.i

rdac.s: rdac.c.s

.PHONY : rdac.s

# target to generate assembly for a file
rdac.c.s:
	$(MAKE) -f CMakeFiles/linDMR.dir/build.make CMakeFiles/linDMR.dir/rdac.c.s
.PHONY : rdac.c.s

scheduler.o: scheduler.c.o

.PHONY : scheduler.o

# target to build an object file
scheduler.c.o:
	$(MAKE) -f CMakeFiles/linDMR.dir/build.make CMakeFiles/linDMR.dir/scheduler.c.o
.PHONY : scheduler.c.o

scheduler.i: scheduler.c.i

.PHONY : scheduler.i

# target to preprocess a source file
scheduler.c.i:
	$(MAKE) -f CMakeFiles/linDMR.dir/build.make CMakeFiles/linDMR.dir/scheduler.c.i
.PHONY : scheduler.c.i

scheduler.s: scheduler.c.s

.PHONY : scheduler.s

# target to generate assembly for a file
scheduler.c.s:
	$(MAKE) -f CMakeFiles/linDMR.dir/build.make CMakeFiles/linDMR.dir/scheduler.c.s
.PHONY : scheduler.c.s

smaster.o: smaster.c.o

.PHONY : smaster.o

# target to build an object file
smaster.c.o:
	$(MAKE) -f CMakeFiles/linDMR.dir/build.make CMakeFiles/linDMR.dir/smaster.c.o
.PHONY : smaster.c.o

smaster.i: smaster.c.i

.PHONY : smaster.i

# target to preprocess a source file
smaster.c.i:
	$(MAKE) -f CMakeFiles/linDMR.dir/build.make CMakeFiles/linDMR.dir/smaster.c.i
.PHONY : smaster.c.i

smaster.s: smaster.c.s

.PHONY : smaster.s

# target to generate assembly for a file
smaster.c.s:
	$(MAKE) -f CMakeFiles/linDMR.dir/build.make CMakeFiles/linDMR.dir/smaster.c.s
.PHONY : smaster.c.s

sqlite.o: sqlite.c.o

.PHONY : sqlite.o

# target to build an object file
sqlite.c.o:
	$(MAKE) -f CMakeFiles/linDMR.dir/build.make CMakeFiles/linDMR.dir/sqlite.c.o
.PHONY : sqlite.c.o

sqlite.i: sqlite.c.i

.PHONY : sqlite.i

# target to preprocess a source file
sqlite.c.i:
	$(MAKE) -f CMakeFiles/linDMR.dir/build.make CMakeFiles/linDMR.dir/sqlite.c.i
.PHONY : sqlite.c.i

sqlite.s: sqlite.c.s

.PHONY : sqlite.s

# target to generate assembly for a file
sqlite.c.s:
	$(MAKE) -f CMakeFiles/linDMR.dir/build.make CMakeFiles/linDMR.dir/sqlite.c.s
.PHONY : sqlite.c.s

users.o: users.c.o

.PHONY : users.o

# target to build an object file
users.c.o:
	$(MAKE) -f CMakeFiles/linDMR.dir/build.make CMakeFiles/linDMR.dir/users.c.o
.PHONY : users.c.o

users.i: users.c.i

.PHONY : users.i

# target to preprocess a source file
users.c.i:
	$(MAKE) -f CMakeFiles/linDMR.dir/build.make CMakeFiles/linDMR.dir/users.c.i
.PHONY : users.c.i

users.s: users.c.s

.PHONY : users.s

# target to generate assembly for a file
users.c.s:
	$(MAKE) -f CMakeFiles/linDMR.dir/build.make CMakeFiles/linDMR.dir/users.c.s
.PHONY : users.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... linDMR"
	@echo "... edit_cache"
	@echo "... BPTC1969.o"
	@echo "... BPTC1969.i"
	@echo "... BPTC1969.s"
	@echo "... aprs.o"
	@echo "... aprs.i"
	@echo "... aprs.s"
	@echo "... convbin.o"
	@echo "... convbin.i"
	@echo "... convbin.s"
	@echo "... decode34Rate.o"
	@echo "... decode34Rate.i"
	@echo "... decode34Rate.s"
	@echo "... dmr.o"
	@echo "... dmr.i"
	@echo "... dmr.s"
	@echo "... hyteraDecode.o"
	@echo "... hyteraDecode.i"
	@echo "... hyteraDecode.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... rdac.o"
	@echo "... rdac.i"
	@echo "... rdac.s"
	@echo "... scheduler.o"
	@echo "... scheduler.i"
	@echo "... scheduler.s"
	@echo "... smaster.o"
	@echo "... smaster.i"
	@echo "... smaster.s"
	@echo "... sqlite.o"
	@echo "... sqlite.i"
	@echo "... sqlite.s"
	@echo "... users.o"
	@echo "... users.i"
	@echo "... users.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

